// In-memory Store Fallback for Vercel production when MongoDB URI is not configured yet.

export const memoryStore = {
  settings: {
    _id: "default_settings_id",
    restaurantName: "Ceylon Curry",
    address: "44 Mayflower St, Plymouth PL1 1QX",
    mobileNumber: "01752 941504",
    whatsappNumber: "+447824110369",
    restaurantEmail: "info@ceyloncurry.co.uk",
    adminEmail: "apptronorders@gmail.com",
    openingHours: {
      monday: "12:00 PM - 10:00 PM",
      tuesday: "12:00 PM - 10:00 PM",
      wednesday: "12:00 PM - 10:00 PM",
      thursday: "12:00 PM - 10:00 PM",
      friday: "12:00 PM - 11:00 PM",
      saturday: "12:00 PM - 11:00 PM",
      sunday: "12:00 PM - 09:30 PM",
    },
    socialLinks: {
      facebook: "https://www.facebook.com/ceyloncurrysl/",
      instagram: "https://www.instagram.com/ceyloncurrys/",
      tiktok: "https://www.tiktok.com/@ceylon.curry.plym",
    },
    currency: "£",
    reservationSettings: {
      reservationDurationMinutes: 60,
      minNoticeHours: 1,
      maxAdvanceDays: 30,
    },
  },

  tables: [
    { _id: "tbl_1", tableNumber: 1, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_2", tableNumber: 2, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_3", tableNumber: 3, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_4", tableNumber: 4, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_5", tableNumber: 5, capacity: 4, type: "Family", status: "Available" },
    { _id: "tbl_6", tableNumber: 6, capacity: 4, type: "Family", status: "Available" },
    { _id: "tbl_7", tableNumber: 7, capacity: 4, type: "Family", status: "Available" },
  ],

  categories: [
    { _id: "cat_1", name: "Snacks", slug: "snacks", description: "Crispy Sri Lankan and Kerala short eats, rolls and vadais", displayOrder: 1 },
    { _id: "cat_2", name: "Starters", slug: "starters", description: "Spicy appetizers, soups and crispy snacks", displayOrder: 2 },
    { _id: "cat_3", name: "The Fry Station", slug: "fry-station", description: "Kerala-style fried meat, fish and sides", displayOrder: 3 },
    { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta", description: "Traditional Ceylon shredded parotta stir-fry with meat, egg or veg", displayOrder: 4 },
    { _id: "cat_5", name: "Kothu – Puttu", slug: "kothu-puttu", description: "Steamed cylindrical ground rice and coconut layers stir-fried with curry", displayOrder: 5 },
    { _id: "cat_6", name: "Biryani", slug: "biryani", description: "Aromatic biryanis served in Kerala or Ambur styles", displayOrder: 6 },
    { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles", description: "Wok-tossed rice and noodles with authentic flavors", displayOrder: 7 },
    { _id: "cat_8", name: "Dosa", slug: "dosa", description: "Crispy South Indian thin rice crepes served with sambar and chutney", displayOrder: 8 },
    { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats", description: "Traditional Sri Lankan and South Indian staples like hoppers, poori, puttu and parotta", displayOrder: 9 },
    { _id: "cat_10", name: "Curry", slug: "curry", description: "Rich, slow-cooked Ceylon and Kerala style meat, fish and vegetarian curries", displayOrder: 10 },
    { _id: "cat_11", name: "Desserts", slug: "desserts", description: "Sweet treats including traditional Watalappam, Payasam and puddings", displayOrder: 11 },
    { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals", description: "Plentiful thalis, special lunch/dinner boxes and traditional lamp rice", displayOrder: 12 },
  ],

  products: [
    // === SNACKS ===
    {
      _id: "prod_1",
      name: "Veg Bonda",
      slug: "veg-bonda",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Deep-fried savory spiced vegetable ball. Special Offer: 2 for £3.00",
      description: "A popular Sri Lankan and South Indian tea-time snack. Spiced mashed potatoes and mixed vegetables shaped into rounds, dipped in gram flour batter, and deep-fried to golden perfection. Special Offer: 2 for £3.00.",
      price: 1.79,
      originalPrice: 1.79,
      isOffer: false,
      ingredients: ["Potatoes", "Carrots", "Beans", "Spices", "Gram Flour"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_2",
      name: "Sweet Bonda",
      slug: "sweet-bonda",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Sweet fried snack made with wheat, banana, and sugar. Special Offer: 2 for £3.00",
      description: "Crispy on the outside, soft and sweet on the inside. A perfect sweet treat made with wheat flour, ripe bananas, sugar, and cardamom. Special Offer: 2 for £3.00.",
      price: 1.79,
      originalPrice: 1.79,
      isOffer: false,
      ingredients: ["Wheat Flour", "Banana", "Sugar", "Cardamom"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_3",
      name: "Egg & Fish Roll",
      slug: "egg-fish-roll",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Crispy breaded pancake roll filled with spiced fish and boiled egg. Special Offer: 2 for £3.49",
      description: "A Sri Lankan bakery classic. Thin pancake wrapper rolled around a savory filling of spiced mackerel fish, potatoes, and boiled egg, breaded and deep-fried. Special Offer: 2 for £3.49.",
      price: 1.99,
      originalPrice: 1.99,
      isOffer: false,
      ingredients: ["Mackerel Fish", "Potato", "Boiled Egg", "Breadcrumbs", "Spices"],
      allergens: ["Gluten", "Fish", "Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_4",
      name: "Fish Cutlet",
      slug: "fish-cutlet",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Crispy spiced mackerel fish and potato croquette. Special Offer: 2 for £3.00",
      description: "Traditional Sri Lankan short eat. Small round balls of seasoned fish, potatoes, ginger, and green chilies coated in breadcrumbs and fried. Special Offer: 2 for £3.00.",
      price: 1.79,
      originalPrice: 1.79,
      isOffer: false,
      ingredients: ["Mackerel Fish", "Potato", "Onions", "Green Chili", "Breadcrumbs"],
      allergens: ["Gluten", "Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_5",
      name: "Mutton Roll",
      slug: "mutton-roll",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Crispy breaded short-crust roll filled with spiced minced mutton and potato. Special Offer: 2 for £3.00",
      description: "Delectable crispy roll filled with spiced minced mutton, braised potatoes, onions, and curry leaves. Special Offer: 2 for £3.00.",
      price: 1.79,
      originalPrice: 1.79,
      isOffer: false,
      ingredients: ["Minced Mutton", "Potato", "Curry Leaves", "Onions", "Breadcrumbs"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_6",
      name: "Chicken Roll",
      slug: "chicken-roll",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Crispy breaded roll filled with seasoned chicken and potato. Special Offer: 2 for £3.00",
      description: "Popular Sri Lankan short eat. Breaded savory roll stuffed with seasoned shredded chicken, potatoes, and signature spices. Special Offer: 2 for £3.00.",
      price: 1.79,
      originalPrice: 1.79,
      isOffer: false,
      ingredients: ["Chicken", "Potato", "Onions", "Spices", "Breadcrumbs"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_7",
      name: "Ulundu Vadai",
      slug: "ulundu-vadai",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Savory fried lentil donut made with urad dal, onions, and green chilies. Special Offer: 2 for £3.00",
      description: "Crispy, golden brown, donut-shaped fritter made from black gram (urad dal) batter mixed with peppercorns, curry leaves, ginger, and green chilies. Special Offer: 2 for £3.00.",
      price: 1.70,
      originalPrice: 1.70,
      isOffer: false,
      ingredients: ["Black Gram", "Ginger", "Green Chili", "Onions", "Curry Leaves"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_8",
      name: "Kadalai Vadai",
      slug: "kadalai-vadai",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Crunchy fried split chickpea fritter spiced with chili and curry leaves. Special Offer: 2 for £3.00",
      description: "Crunchy tea-time snack made of coarsely ground chana dal (chickpeas) mixed with fennel seeds, dried red chilies, chopped onions, and fresh curry leaves. Special Offer: 2 for £3.00.",
      price: 1.70,
      originalPrice: 1.70,
      isOffer: false,
      ingredients: ["Split Chickpeas", "Fennel Seeds", "Red Chili", "Curry Leaves", "Onions"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_9",
      name: "Pazham Pori (Kerala)",
      slug: "pazham-pori",
      categoryId: { _id: "cat_1", name: "Snacks", slug: "snacks" },
      shortDescription: "Traditional Kerala sweet banana fritters fried to golden brown.",
      description: "Authentic Kerala snack made by dipping ripe plantain slices in a sweetened flour batter and deep-frying them until crispy and golden.",
      price: 1.59,
      originalPrice: 1.59,
      isOffer: false,
      ingredients: ["Ripe Plantain", "All-Purpose Flour", "Sugar", "Cardamom"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },

    // === STARTERS ===
    {
      _id: "prod_10",
      name: "Chicken 65",
      slug: "chicken-65",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Fiery, deep-fried chicken marinated in ginger, garlic, red chilies, and curry leaves.",
      description: "Classic spicy appetizer featuring bite-sized chicken pieces marinated in local spices, yogurt, curry leaves, and deep-fried to a juicy crunch.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Chicken Pieces", "Yogurt", "Ginger", "Garlic", "Red Chili", "Curry Leaves"],
      allergens: ["Milk"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_11",
      name: "Mushroom 65",
      slug: "mushroom-65",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Crispy, spiced batter-fried fresh button mushrooms.",
      description: "A vegetarian delight. Fresh button mushrooms tossed in a hot and spicy marinade of ginger, garlic, and red chilies, then fried crispy.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Button Mushrooms", "Spices", "Ginger-Garlic Paste", "Curry Leaves"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_12",
      name: "Cauliflower 65",
      slug: "cauliflower-65",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Crispy fried cauliflower florets marinated in south Indian spices (Gobi 65).",
      description: "Crispy, spicy cauliflower florets tossed with curry leaves, yogurt, and aromatic spices. Perfectly fried.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Cauliflower", "Ginger", "Garlic", "Yogurt", "Curry Leaves", "Spices"],
      allergens: ["Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_13",
      name: "Prawn 65",
      slug: "prawn-65",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Crispy fried marinated prawns tossed with green chilies and curry leaves.",
      description: "Juicy king prawns marinated in a fiery blend of ginger, garlic, yogurt, and red chili powder, fried until crisp.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["King Prawns", "Yogurt", "Red Chili", "Ginger-Garlic", "Curry Leaves"],
      allergens: ["Crustaceans", "Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_14",
      name: "Paneer 65",
      slug: "paneer-65",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Crispy fried cubes of paneer cottage cheese tossed in spicy yogurt glaze.",
      description: "Indo-Chinese style appetizer featuring crispy fried paneer cubes seasoned with curry leaves, mustard seeds, and yogurt chili sauce.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Paneer Cottage Cheese", "Yogurt", "Mustard Seeds", "Curry Leaves", "Soy Sauce"],
      allergens: ["Milk", "Soy"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_15",
      name: "Prawn Pepper Fry",
      slug: "prawn-pepper-fry",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "King prawns tossed with black pepper, caramelized onions, and curry leaves.",
      description: "Fiery dry prawn starter seasoned with coarse black pepper, green chilies, ginger-garlic paste, and fried onions.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["King Prawns", "Black Pepper", "Onions", "Ginger-Garlic", "Curry Leaves"],
      allergens: ["Crustaceans"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_16",
      name: "Chicken Manchurian",
      slug: "chicken-manchurian",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Crispy chicken chunks tossed in sweet, tangy, and slightly spicy Manchurian sauce.",
      description: "Popular Indo-Chinese dish made with fried chicken balls tossed in a thick, savory gravy flavored with soy sauce, garlic, and ginger.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Chicken", "Soy Sauce", "Ginger", "Garlic", "Spring Onions", "Corn Flour"],
      allergens: ["Gluten", "Soy"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_17",
      name: "Crab Soup",
      slug: "crab-soup",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Spicy and warm soup prepared with crab meat, pepper, and local herbs.",
      description: "Tangy and fiery broth infused with crab pieces, crushed black pepper, garlic, and fresh coriander. Great for warming up.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Crab Meat", "Black Pepper", "Garlic", "Spices", "Coriander"],
      allergens: ["Crustaceans"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_18",
      name: "Chicken Soup",
      slug: "chicken-soup",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Nourishing spiced chicken broth with herbs and cracked black pepper.",
      description: "Nourishing, slow-simmered chicken soup prepared with traditional spices, crushed pepper, garlic, and fresh herbs.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Chicken Broth", "Black Pepper", "Garlic", "Spices", "Fresh Herbs"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_19",
      name: "Pappadam",
      slug: "pappadam",
      categoryId: { _id: "cat_2", name: "Starters", slug: "starters" },
      shortDescription: "Crispy thin lentil wafers fried to a perfect crunch (3 pcs).",
      description: "Traditional thin, crispy fried papadums made from seasoned black gram flour. A perfect side for any meal.",
      price: 1.49,
      originalPrice: 1.49,
      isOffer: false,
      ingredients: ["Black Gram Flour", "Salt", "Coconut Oil"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80" }],
    },

    // === THE FRY STATION ===
    {
      _id: "prod_20",
      name: "Beef Fry",
      slug: "beef-fry",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Authentic Kerala-style slow-roasted beef chunks with coconut slices and black pepper (Beef Ularthiyathu).",
      description: "Traditional Kerala delicacy. Beef chunks slow-cooked with turmeric, coriander, and chili, then roasted with coconut bites, curry leaves, and freshly crushed black pepper.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Beef Chunks", "Coconut Slices", "Black Pepper", "Curry Leaves", "Spices"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_21",
      name: "Kerala Style Chicken Fry",
      slug: "kerala-style-chicken-fry",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Bone-in chicken marinated in Kerala spices and fried with curry leaves.",
      description: "Juicy chicken pieces marinated in hot spices, ginger-garlic paste, and fennel, then deep-fried alongside fresh curry leaves and green chilies.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Bone-in Chicken", "Kerala Spices", "Fennel Seeds", "Ginger-Garlic", "Curry Leaves"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_22",
      name: "Fish Fry",
      slug: "fish-fry",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Pan-fried fish steak marinated in red chili, turmeric, and lemon juice.",
      description: "Traditional fish steak marinated in fresh ginger-garlic, red chili powder, turmeric, and local spices, shallow-fried to perfection.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Fish Steak", "Red Chili Powder", "Turmeric", "Lemon Juice", "Ginger-Garlic"],
      allergens: ["Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_23",
      name: "Full Fish Fry",
      slug: "full-fish-fry",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Whole fish marinated in authentic spices and deep-fried.",
      description: "Whole fresh fish scored and marinated in a rich paste of chili, ginger, garlic, fennel, and lemon juice, then deep-fried until outer crust is crispy.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: false,
      ingredients: ["Whole Fish", "Ginger", "Garlic", "Red Chili Paste", "Lemon juice", "Fennel"],
      allergens: ["Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_24",
      name: "Omelette",
      slug: "omelette",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Fluffy omelette cooked with chopped onions, green chilies, and black pepper.",
      description: "Sri Lankan/Indian style fluffy egg omelette made with fresh eggs, red onions, green chilies, and cracked black pepper.",
      price: 2.99,
      originalPrice: 2.99,
      isOffer: false,
      ingredients: ["Eggs", "Red Onions", "Green Chili", "Black Pepper"],
      allergens: ["Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_25",
      name: "Potato Chips Fry",
      slug: "potato-chips-fry",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Crispy fried fresh potato slices dusted with salt and mild spice.",
      description: "House-made potato chips fried golden brown and lightly seasoned with salt and a touch of chili powder.",
      price: 2.49,
      originalPrice: 2.49,
      isOffer: false,
      ingredients: ["Fresh Potatoes", "Salt", "Red Chili Powder"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_26",
      name: "Neththoli Fry",
      slug: "neththoli-fry",
      categoryId: { _id: "cat_3", name: "The Fry Station", slug: "fry-station" },
      shortDescription: "Crispy deep-fried anchovies seasoned with chili, turmeric, and curry leaves.",
      description: "Fresh anchovies (netholi) marinated in a spicy rice flour batter, deep-fried until crunchy. An absolute favorite snack from Kerala's coast.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Anchovies", "Rice Flour", "Chili Powder", "Turmeric", "Curry Leaves"],
      allergens: ["Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=800&q=80" }],
    },

    // === KOTHU – PAROTTA ===
    {
      _id: "prod_27",
      name: "Mutton Kothu",
      slug: "mutton-kothu",
      categoryId: { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta" },
      shortDescription: "Shredded flatbread (parotta) stir-fried with spiced mutton, egg, onions, and curry sauce.",
      description: "Sizzling Sri Lankan street classic. Shredded parotta stir-fried on a flat iron griddle with tender mutton chunks, scrambled eggs, onions, green chilies, and rich gravy.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Flaky Parotta", "Tender Mutton", "Eggs", "Onions", "Curry Gravy"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_28",
      name: "Chicken Kothu",
      slug: "chicken-kothu",
      categoryId: { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta" },
      shortDescription: "Shredded parotta stir-fried with spiced chicken, egg, and vegetables on a hot griddle.",
      description: "Sizzling street food favorite. Shredded parotta stir-fried on a flat iron griddle with spiced chicken curry, scrambled eggs, onions, and fresh leeks.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Flaky Parotta", "Spiced Chicken", "Eggs", "Onions", "Leeks", "Gravy"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_29",
      name: "Sea Food Kothu",
      slug: "sea-food-kothu",
      categoryId: { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta" },
      shortDescription: "Iron-griddle shredded parotta stir-fried with mixed seafood, egg, and curry spices.",
      description: "Shredded parotta stir-fried with a mix of prawns, squid, and fish, tossed with scrambled egg, onions, leeks, and seafood curry gravy.",
      price: 11.99,
      originalPrice: 11.99,
      isOffer: false,
      ingredients: ["Flaky Parotta", "Prawns", "Squid", "Fish Pieces", "Eggs", "Leeks", "Seafood Curry"],
      allergens: ["Gluten", "Eggs", "Crustaceans", "Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_30",
      name: "Veg Kothu",
      slug: "veg-kothu",
      categoryId: { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta" },
      shortDescription: "Shredded parotta stir-fried with assorted vegetables, spices, and curry sauce.",
      description: "Delicious vegetarian option. Fluffy parotta shredded and stir-fried with carrots, cabbage, onions, green chilies, and aromatic veg korma gravy.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Flaky Parotta", "Carrots", "Cabbage", "Onions", "Green Chili", "Vegetable Korma"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_31",
      name: "Egg Kothu",
      slug: "egg-kothu",
      categoryId: { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta" },
      shortDescription: "Shredded parotta stir-fried with scrambled eggs, onions, and mild spices.",
      description: "Simple yet flavorful. Shredded parotta tossed on a hot griddle with scrambled eggs, red onions, curry leaves, and spiced gravy.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Flaky Parotta", "Eggs", "Red Onions", "Curry Leaves", "Spiced Gravy"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_32",
      name: "Mixed Kothu",
      slug: "mixed-kothu",
      categoryId: { _id: "cat_4", name: "Kothu – Parotta", slug: "kothu-parotta" },
      shortDescription: "Ultimate combination of chicken, mutton, seafood, and egg stir-fried with shredded parotta.",
      description: "The grand feast! Shredded parotta stir-fried with chicken, mutton, mixed seafood, and scrambled eggs, spiced with rich curry gravies.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: false,
      ingredients: ["Flaky Parotta", "Chicken", "Mutton", "Prawns", "Squid", "Eggs", "Spiced Gravy"],
      allergens: ["Gluten", "Eggs", "Crustaceans", "Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80" }],
    },

    // === KOTHU – PUTTU ===
    {
      _id: "prod_33",
      name: "Mutton Kothu (Puttu)",
      slug: "mutton-kothu-puttu",
      categoryId: { _id: "cat_5", name: "Kothu – Puttu", slug: "kothu-puttu" },
      shortDescription: "Crumbled steamed rice and coconut logs (puttu) stir-fried with spiced mutton, egg, and curry.",
      description: "A unique Sri Lankan delicacy. Steamed puttu (ground rice and coconut) crumbled and stir-fried on a hot griddle with spiced mutton curry, scrambled egg, onions, and chilies.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Crumbled Puttu", "Steamed Coconut", "Mutton Pieces", "Eggs", "Curry Sauce"],
      allergens: ["Eggs"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_34",
      name: "Chicken Kothu (Puttu)",
      slug: "chicken-kothu-puttu",
      categoryId: { _id: "cat_5", name: "Kothu – Puttu", slug: "kothu-puttu" },
      shortDescription: "Steamed puttu crumbled and stir-fried with spiced chicken curry, egg, and vegetables.",
      description: "Flavorful street food twist. Steamed puttu tossed on a griddle with tender chicken pieces, scrambled egg, onions, leeks, and chicken curry sauce.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Crumbled Puttu", "Steamed Coconut", "Tender Chicken", "Eggs", "Leeks", "Spices"],
      allergens: ["Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80" }],
    },

    // === BIRYANI ===
    {
      _id: "prod_35",
      name: "Chicken Biryani (Ambur / Kerala)",
      slug: "chicken-biryani-ambur-kerala",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Fragrant short-grain rice cooked with spiced chicken, mint, coriander, and slow-dum spices.",
      description: "Authentic dum biryani made with fragrant rice (Seeraga Samba / Jeerakasala) cooked slowly with tender chicken, mint, coriander, and traditional South Indian spices.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Seeraga Samba Rice", "Chicken", "Mint", "Coriander", "Dum Spices"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_36",
      name: "Mutton Biryani (Ambur / Kerala)",
      slug: "mutton-biryani-ambur-kerala",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Aromatic spiced rice cooked in dum style with tender bone-in mutton chunks.",
      description: "Deliciously spiced biryani prepared in Ambur or Kerala style with fragrant rice and slow-cooked mutton, sealing in all the rich aromas.",
      price: 11.99,
      originalPrice: 11.99,
      isOffer: false,
      ingredients: ["Seeraga Samba Rice", "Mutton Chunks", "Yogurt", "Caramelized Onions", "Fennel Seeds"],
      allergens: ["Milk"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_37",
      name: "Beef Biryani (Kerala)",
      slug: "beef-biryani-kerala",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Malabar style fragrant rice dum-cooked with rich Kerala beef curry.",
      description: "Authentic Kerala-style beef biryani, layered with fragrant rice, rich caramelized onions, spiced beef masala, and steamed in dum style.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: false,
      ingredients: ["Jeerakasala Rice", "Beef Masala", "Caramelized Onions", "Clarified Butter", "Cashews"],
      allergens: ["Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_38",
      name: "Couple Biryani (Chicken)",
      slug: "couple-biryani-chicken",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Generous platter of Chicken Biryani served with raita and pickle, perfect for two.",
      description: "A shared feast! Large portion of chicken biryani with tender chicken pieces, boiled eggs, served with raita and pickle, sufficient for two.",
      price: 23.99,
      originalPrice: 23.99,
      isOffer: false,
      ingredients: ["Biryani Rice", "Chicken", "Boiled Eggs", "Raita", "Pickle"],
      allergens: ["Eggs", "Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_39",
      name: "Couple Biryani (Mutton)",
      slug: "couple-biryani-mutton",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Deliciously spiced Mutton Biryani platter sized for two persons.",
      description: "A double-portion platter of authentic mutton biryani served with boiled eggs, raita, and pickle. Perfect for a cozy couple dinner.",
      price: 25.99,
      originalPrice: 25.99,
      isOffer: false,
      ingredients: ["Biryani Rice", "Mutton Chunks", "Boiled Eggs", "Raita", "Pickle"],
      allergens: ["Eggs", "Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_40",
      name: "Couple Biryani (Beef)",
      slug: "couple-biryani-beef",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Double-sized Malabar style Beef Biryani platter served with classic sides.",
      description: "A rich and heavy platter of Kerala beef biryani, perfect for sharing. Serves two, accompanied by boiled eggs, raita, and pickle.",
      price: 27.99,
      originalPrice: 27.99,
      isOffer: false,
      ingredients: ["Jeerakasala Rice", "Beef Curry", "Eggs", "Raita", "Pickle"],
      allergens: ["Eggs", "Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_41",
      name: "Chicken Mandi Biryani",
      slug: "chicken-mandi-biryani",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Yemeni-style spiced rice with roasted chicken, infused with smoke.",
      description: "A fragrant rice dish prepared with whole mandi spices, served with tender oven-cooked roasted chicken, and infused with charcoal smoke for that signature aroma.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: false,
      ingredients: ["Long Grain Basmati", "Mandi Spices", "Roasted Chicken", "Smoky Charcoal"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_42",
      name: "Veg Biryani",
      slug: "veg-biryani",
      categoryId: { _id: "cat_6", name: "Biryani", slug: "biryani" },
      shortDescription: "Aromatic basmati rice cooked with fresh seasonal vegetables and biryani spices.",
      description: "A light yet flavorful dum biryani packed with fresh carrots, green beans, peas, and potatoes, seasoned with mint, coriander, and saffron.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Basmati Rice", "Mixed Vegetables", "Saffron", "Mint", "Coriander", "Spices"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80" }],
    },

    // === FRIED RICE & NOODLES ===
    {
      _id: "prod_43",
      name: "Veg Fried Rice",
      slug: "veg-fried-rice",
      categoryId: { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles" },
      shortDescription: "Wok-tossed basmati rice with finely chopped carrots, beans, spring onions, and soy sauce.",
      description: "Indo-Chinese style vegetable fried rice, wok-tossed with aromatic basmati rice, mixed garden vegetables, and light sesame soy sauce.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Basmati Rice", "Carrots", "Green Beans", "Spring Onions", "Soy Sauce"],
      allergens: ["Soy", "Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_44",
      name: "Chicken Fried Rice",
      slug: "chicken-fried-rice",
      categoryId: { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles" },
      shortDescription: "Wok-tossed rice with shredded chicken, scrambled eggs, and vegetables.",
      description: "Tasty wok-fried rice containing tender shredded chicken, scrambled farm eggs, carrots, leeks, and spring onions.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Basmati Rice", "Shredded Chicken", "Eggs", "Carrots", "Leeks", "Soy Sauce"],
      allergens: ["Eggs", "Soy", "Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_45",
      name: "Special Fried Rice",
      slug: "special-fried-rice",
      categoryId: { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles" },
      shortDescription: "Wok-fried rice with a combination of chicken, prawns, and egg.",
      description: "Premium fried rice tossed with tender chicken pieces, fresh prawns, scrambled egg, and crisp vegetables with chef's seasoning.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Basmati Rice", "Chicken", "Prawns", "Eggs", "Mixed Vegetables", "Spices"],
      allergens: ["Eggs", "Crustaceans", "Soy", "Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_46",
      name: "Ceylon Curry Special Fried Rice",
      slug: "ceylon-curry-special-fried-rice",
      categoryId: { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles" },
      shortDescription: "Signature house-spiced fried rice with mixed meats, seafood, and a touch of Ceylon spices.",
      description: "Our ultimate house-special fried rice. Spiced with a touch of roasted Ceylon curry powder, stir-fried with chicken, mutton, prawns, egg, and fresh scallions.",
      price: 11.99,
      originalPrice: 11.99,
      isOffer: false,
      ingredients: ["Basmati Rice", "Chicken", "Mutton", "Prawns", "Egg", "Ceylon Spices"],
      allergens: ["Eggs", "Crustaceans", "Soy", "Gluten"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_47",
      name: "Chicken Noodle",
      slug: "chicken-noodle",
      categoryId: { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles" },
      shortDescription: "Stir-fried noodles with chicken, egg, cabbage, and carrots.",
      description: "Savory wok-tossed noodles with strips of seasoned chicken, scrambled egg, julienned vegetables, and light soy seasoning.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Wheat Noodles", "Shredded Chicken", "Eggs", "Cabbage", "Carrots", "Soy Sauce"],
      allergens: ["Gluten", "Eggs", "Soy"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_48",
      name: "Veg Noodle",
      slug: "veg-noodle",
      categoryId: { _id: "cat_7", name: "Fried Rice & Noodles", slug: "fried-rice-noodles" },
      shortDescription: "Stir-fried noodles with crisp garden vegetables and Chinese spices.",
      description: "Wok-tossed soft noodles packed with carrots, cabbage, bell peppers, spring onions, and seasoned with soy sauce and white pepper.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Wheat Noodles", "Carrots", "Cabbage", "Bell Peppers", "Spring Onions", "Soy Sauce"],
      allergens: ["Gluten", "Soy"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80" }],
    },

    // === DOSA ===
    {
      _id: "prod_49",
      name: "Masala Dosa",
      slug: "masala-dosa",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "Crispy rice and lentil crepe stuffed with spiced potato mash, served with sambar and chutneys.",
      description: "Classic South Indian crepe made from fermented rice and lentil batter, rolled with a savory filling of spiced potato-onion mash. Served with hot sambar, coconut, and tomato chutneys.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Fermented Rice Batter", "Potatoes", "Onions", "Spices", "Chutney", "Sambar"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_50",
      name: "Ghee Dosa",
      slug: "ghee-dosa",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "Crispy, paper-thin crepe roasted with pure cow's ghee.",
      description: "Golden, crispy thin crepe drizzled generously with clarified butter (ghee) during roasting. Served with sambar and chutneys.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Fermented Rice Batter", "Clarified Butter (Ghee)", "Chutney", "Sambar"],
      allergens: ["Milk", "Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_51",
      name: "Plain Dosa",
      slug: "plain-dosa",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "Crispy thin rice and lentil crepe served with sambar and coconut chutney.",
      description: "Traditional fermented rice-lentil crepe, light and crispy. Served with fresh coconut chutney, red chutney, and vegetable sambar.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Fermented Rice Batter", "Chutney", "Sambar"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_52",
      name: "Paneer Masala Dosa",
      slug: "paneer-masala-dosa",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "Crispy crepe stuffed with spiced shredded cottage cheese (paneer) filling.",
      description: "A delicious twist. Crispy rice crepe filled with grated paneer cooked with onions, tomatoes, ginger, and green chilies. Served with sambar and chutneys.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Fermented Rice Batter", "Paneer", "Onions", "Tomatoes", "Ginger", "Chutney"],
      allergens: ["Milk", "Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_53",
      name: "Ceylon Dosa (4)",
      slug: "ceylon-dosa-4",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "Set of 4 small, soft, and thick Sri Lankan style dosas.",
      description: "Four soft, sponge-like small dosas cooked in Sri Lankan style, thick and fluffy. Served with spicy onion sambol (Lunu Miris) and potato curry or sambar.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Thick Dosa Batter", "Lunu Miris", "Sambar / Potato Curry"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_54",
      name: "Sambar Vadai (2)",
      slug: "sambar-vadai-2",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "2 pieces of savory lentil donuts soaked in hot piping vegetable sambar.",
      description: "Two crispy urad dal vadais immersed in a bowl of aromatic, steaming vegetable lentil stew (sambar), topped with fresh coriander.",
      price: 4.99,
      originalPrice: 4.99,
      isOffer: false,
      ingredients: ["Urad Dal Vadais", "Sambar Stew", "Fresh Coriander"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_55",
      name: "Egg Dosa",
      slug: "egg-dosa",
      categoryId: { _id: "cat_8", name: "Dosa", slug: "dosa" },
      shortDescription: "Crispy crepe coated with scrambled egg, pepper, and onions.",
      description: "Fermented rice-lentil crepe with a layer of egg spread on the inside while cooking, sprinkled with red onions and black pepper. Served with sambar and chutneys.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Fermented Rice Batter", "Eggs", "Red Onions", "Black Pepper", "Chutney"],
      allergens: ["Eggs", "Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80" }],
    },

    // === SOUTH ASIAN EATS ===
    {
      _id: "prod_56",
      name: "Poori Masala",
      slug: "poori-masala",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "2 fluffy deep-fried wheat breads served with spiced potato masala.",
      description: "Golden-brown puffed deep-fried whole wheat flatbreads (poori) served with a traditional tempered potato and onion curry.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Whole Wheat Flour", "Potatoes", "Onions", "Mustard Seeds", "Curry Leaves"],
      allergens: ["Gluten", "Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_57",
      name: "Idly (4)",
      slug: "idly-4",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Set of 4 steamed savory rice-and-lentil cakes, served with sambar and chutneys.",
      description: "Soft, fluffy, steamed round cakes made from fermented black lentil and rice batter. Served with sambar and assorted coconut chutneys.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Fermented Rice-Lentil Batter", "Sambar", "Coconut Chutney", "Red Chutney"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_58",
      name: "String Hopper (10)",
      slug: "string-hopper-10",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "10 steamed rice flour noodle nests (Idiyappam) served with coconut sodhi and pol sambol.",
      description: "Classic Sri Lankan breakfast/dinner. Ten steamed nests of fine rice flour noodles, served with warm spiced coconut milk gravy (sodhi) and coconut sambol.",
      price: 4.99,
      originalPrice: 4.99,
      isOffer: false,
      ingredients: ["Rice Flour Noodle Nests", "Coconut Sodhi", "Pol Sambol"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_59",
      name: "String Hopper (25) – Pre Order Only",
      slug: "string-hopper-25",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Platter of 25 steamed string hoppers, perfect for family sharing. Pre-order only.",
      description: "A larger family portion of twenty-five steamed rice noodle nests. Served with coconut milk sodhi and sambol. Needs to be ordered in advance.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Rice Flour Noodle Nests", "Coconut Sodhi", "Pol Sambol"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_60",
      name: "Puttu with Sothi Sambol",
      slug: "puttu-sothi-sambol",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Steamed ground rice and coconut logs served with sodhi and pol sambol.",
      description: "Traditional Sri Lankan steamed cylinder of ground rice layered with grated coconut. Served with a rich coconut milk gravy (sothi) and spicy pol sambol.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Ground Rice", "Grated Coconut", "Sothi Coconut Milk", "Pol Sambol"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_61",
      name: "Parotta",
      slug: "parotta",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Layered, flaky flatbread made from refined flour (1 pc).",
      description: "Authentic south Indian layered flatbread, soft, flaky, and golden-brown. Cooked on a flat grill. Goes perfectly with curries.",
      price: 2.99,
      originalPrice: 2.99,
      isOffer: false,
      ingredients: ["Refined Wheat Flour", "Oil", "Water"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_62",
      name: "Egg Parotta",
      slug: "egg-parotta",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Layered flatbread coated with egg and cooked on the grill.",
      description: "Layered parotta cooked on the griddle with a coating of seasoned beaten egg, red onion, and black pepper.",
      price: 3.99,
      originalPrice: 3.99,
      isOffer: false,
      ingredients: ["Refined Wheat Flour", "Egg", "Onions", "Pepper"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_63",
      name: "Ceylon Coconut Rotty (Pol Rotty)",
      slug: "ceylon-coconut-rotty-pol-rotty",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Traditional rustic Sri Lankan coconut flatbread (2 pcs).",
      description: "Two rustic flatbreads made with wheat flour, grated fresh coconut, red onions, green chilies, and curry leaves, cooked on a clay or iron griddle. Served with lunu miris (spicy onion paste).",
      price: 3.49,
      originalPrice: 3.49,
      isOffer: false,
      ingredients: ["Wheat Flour", "Grated Coconut", "Onions", "Green Chili", "Lunu Miris"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_64",
      name: "Plain Hopper",
      slug: "plain-hopper",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Bowl-shaped thin rice pancake with crispy edges and soft center (Appam).",
      description: "Sri Lankan specialty. Crispy, bowl-shaped thin crepe made from fermented rice flour and coconut milk batter, with a soft, spongy center.",
      price: 1.49,
      originalPrice: 1.49,
      isOffer: false,
      ingredients: ["Fermented Rice Flour", "Coconut Milk"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_65",
      name: "Milk Hopper",
      slug: "milk-hopper",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Bowl-shaped hopper with a sweet coconut milk center.",
      description: "Traditional appam cooked with a sweet, thick dollop of coconut cream added to the center, creating a rich sweet center.",
      price: 1.99,
      originalPrice: 1.99,
      isOffer: false,
      ingredients: ["Fermented Rice Flour", "Coconut Cream", "Sugar"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_66",
      name: "Egg Hopper",
      slug: "egg-hopper",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "Bowl-shaped hopper with a soft-boiled egg in the center.",
      description: "Savory appam cooked with a fresh farm egg cracked into the center, lightly seasoned with salt and black pepper.",
      price: 2.49,
      originalPrice: 2.49,
      isOffer: false,
      ingredients: ["Fermented Rice Flour", "Coconut Milk", "Egg", "Black Pepper"],
      allergens: ["Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_67",
      name: "2 Parotta Veg Korma",
      slug: "2-parotta-veg-korma",
      categoryId: { _id: "cat_9", name: "South Asian Eats", slug: "south-asian-eats" },
      shortDescription: "2 flaky parottas served with a rich, aromatic mixed vegetable korma.",
      description: "A complete meal featuring two flaky, layered parottas served with a creamy curry of mixed vegetables cooked in coconut milk, cashew paste, and spices.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Wheat Parotta", "Carrots", "Potatoes", "Coconut Milk", "Cashew Paste"],
      allergens: ["Gluten", "Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80" }],
    },

    // === CURRY ===
    {
      _id: "prod_68",
      name: "Mutton Curry (Kerala / Ceylon)",
      slug: "mutton-curry-kerala-ceylon",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Slow-cooked bone-in mutton simmered in a dark, highly spiced roasted curry powder gravy.",
      description: "Authentic Ceylon or Kerala style mutton curry. Tender pieces of mutton slow-cooked with roasted coriander, cumin, fennel, cardamoms, cinnamon, and thick coconut milk.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Mutton Pieces", "Roasted Curry Powder", "Cardamom", "Cinnamon", "Coconut Milk"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_69",
      name: "Beef Curry (Kerala)",
      slug: "beef-curry-kerala",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Beef slow-simmered in a rich Kerala spice gravy with coconut slices.",
      description: "Traditional Kerala style beef curry cooked with garlic, ginger, green chilies, roasted spices, and garnishing of roasted coconut pieces.",
      price: 11.99,
      originalPrice: 11.99,
      isOffer: false,
      ingredients: ["Beef", "Garlic", "Ginger", "Coconut Slices", "Kerala Spices"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_70",
      name: "Kudal Curry (Beef)",
      slug: "kudal-curry-beef",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Spicy traditional beef tripe curry cooked with local spices.",
      description: "A rustic delicacy. Beef tripe (kudal) cleaned and slow-cooked with a robust spice paste, ginger-garlic, curry leaves, and crushed pepper.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Beef Tripe", "Robust Spices", "Ginger-Garlic", "Curry Leaves", "Black Pepper"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_71",
      name: "Chicken Curry",
      slug: "chicken-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Tender chicken pieces cooked in a classic Sri Lankan spiced coconut gravy.",
      description: "A home-style Ceylon chicken curry simmered with onions, lemongrass, curry leaves, pandan leaves, and roasted spice powder, finished with coconut milk.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Chicken Pieces", "Lemongrass", "Curry Leaves", "Pandan Leaves", "Coconut Milk"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_72",
      name: "Fish Curry",
      slug: "fish-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Tangy and spicy fish curry simmered with tamarind (goraka) and coconut milk.",
      description: "Sri Lankan style fish curry, tangy and spicy, flavored with black tamarind (goraka), fenugreek, garlic, curry leaves, and fresh coconut milk.",
      price: 8.99,
      originalPrice: 8.99,
      isOffer: false,
      ingredients: ["Fish", "Black Tamarind (Goraka)", "Fenugreek", "Garlic", "Coconut Milk"],
      allergens: ["Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_73",
      name: "Potato Curry",
      slug: "potato-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Mild and creamy potato curry cooked in coconut milk (Ala Hodi).",
      description: "Comforting Sri Lankan white curry made of boiled potatoes simmered in a thin, creamy coconut milk gravy seasoned with turmeric, fenugreek, onions, and curry leaves.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Potatoes", "Turmeric", "Fenugreek", "Onions", "Coconut Milk"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_74",
      name: "Cabbage Fry",
      slug: "cabbage-fry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Shredded cabbage stir-fried with mustard seeds, coconut, and turmeric (Cabbage Mallum).",
      description: "A healthy dry side dish. Finely shredded cabbage stir-fried with grated fresh coconut, green chilies, mustard seeds, turmeric, and fresh curry leaves.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Shredded Cabbage", "Grated Coconut", "Mustard Seeds", "Turmeric", "Green Chili"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_75",
      name: "Soya Curry",
      slug: "soya-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Spicy soy chunks curry cooked in a dark roasted Sri Lankan gravy.",
      description: "High-protein soy chunks cooked in a rich, dark gravy seasoned with roasted curry powder, chilies, cardamom, and coconut milk.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Soya Chunks", "Roasted Curry Powder", "Cardamom", "Chilies", "Coconut Milk"],
      allergens: ["Soy"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_76",
      name: "Aubergine & Chickpeas (V)",
      slug: "aubergine-chickpeas",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Rich curry with roasted aubergine slices and tender chickpeas. (Vegan)",
      description: "Roasted aubergine (eggplant) cubes and soft chickpeas cooked in a flavorful Sri Lankan spice paste with tomatoes and coconut milk.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: false,
      ingredients: ["Aubergine", "Chickpeas", "Tomato", "Spices", "Coconut Milk"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_77",
      name: "Spinach Curry (V)",
      slug: "spinach-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Fresh spinach leaves cooked with dhal, garlic, and coconut milk. (Vegan)",
      description: "Comforting green curry made of fresh spinach (cheera) cooked with red lentils, garlic, green chilies, and coconut milk.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Spinach Leaves", "Red Lentils", "Garlic", "Green Chilies", "Coconut Milk"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_78",
      name: "Dhal Curry (V)",
      slug: "dhal-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Red lentils slow-cooked with turmeric, garlic, and tempered with mustard seeds. (Vegan)",
      description: "The ultimate Sri Lankan staple. Red split lentils cooked in coconut milk, tempered in oil with onions, mustard seeds, dry chilies, and curry leaves.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Red Lentils", "Turmeric", "Garlic", "Mustard Seeds", "Coconut Milk", "Curry Leaves"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_79",
      name: "Sambar (V)",
      slug: "sambar",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Traditional South Indian lentil stew packed with mixed vegetables and tamarind broth. (Vegan)",
      description: "Aromatic vegetable lentil stew made with tamarind broth, lentils, drumsticks, carrots, pumpkin, and roasted sambar spice mix.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Lentils", "Mixed Vegetables", "Tamarind Broth", "Sambar Spices"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_80",
      name: "Leeks & Carrot Curry (V)",
      slug: "leeks-carrot-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Lightly spiced stir-fried leeks and carrots with grated coconut. (Vegan)",
      description: "Fresh julienned carrots and sliced leeks sauteed with mustard seeds, onions, green chilies, and tossed with fresh grated coconut.",
      price: 5.99,
      originalPrice: 5.99,
      isOffer: false,
      ingredients: ["Carrots", "Leeks", "Mustard Seeds", "Grated Coconut", "Green Chili"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_81",
      name: "Chicken Tikka Masala",
      slug: "chicken-tikka-masala",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Grilled chicken chunks in a rich, creamy, tomato-based spiced gravy.",
      description: "World-famous curry consisting of marinated chicken pieces grilled in tandoor style and simmered in a creamy, sweet-spiced tomato, onion, and cashew gravy.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Tandoori Chicken Chunks", "Tomato Paste", "Cream", "Cashew Gravy", "Spices"],
      allergens: ["Milk", "Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_82",
      name: "Butter Chicken Curry",
      slug: "butter-chicken-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Tender chicken in a sweet, velvety butter and tomato gravy.",
      description: "Rich and creamy North Indian classic. Grilled chicken cooked in a smooth tomato gravy with butter, cream, and dried fenugreek leaves (kasuri methi).",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Chicken Chunks", "Butter", "Tomato Gravy", "Cream", "Fenugreek Leaves"],
      allergens: ["Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_83",
      name: "Chicken Korma Curry",
      slug: "chicken-korma-curry",
      categoryId: { _id: "cat_10", name: "Curry", slug: "curry" },
      shortDescription: "Mildly spiced chicken curry in a rich cashew and coconut cream sauce.",
      description: "A delicate and aromatic curry featuring chicken simmered in a mild, sweet sauce made of cashew nut paste, yogurt, cardamom, and coconut cream.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Chicken pieces", "Cashew Paste", "Yogurt", "Coconut Cream", "Cardamom"],
      allergens: ["Milk", "Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },

    // === DESSERTS ===
    {
      _id: "prod_84",
      name: "Watalappam (S)",
      slug: "watalappam-s",
      categoryId: { _id: "cat_11", name: "Desserts", slug: "desserts" },
      shortDescription: "Small portion of traditional steamed coconut jaggery cardamom custard.",
      description: "Traditional Sri Lankan baked custard made of rich coconut milk, dark kitul jaggery, eggs, and cardamoms, topped with cashew nuts. Small portion.",
      price: 2.99,
      originalPrice: 2.99,
      isOffer: false,
      ingredients: ["Kitul Jaggery", "Coconut Milk", "Eggs", "Cardamom", "Cashews"],
      allergens: ["Eggs", "Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_85",
      name: "Watalappam (R)",
      slug: "watalappam-r",
      categoryId: { _id: "cat_11", name: "Desserts", slug: "desserts" },
      shortDescription: "Regular portion of classic Sri Lankan spiced coconut jaggery custard.",
      description: "Classic Sri Lankan royal dessert made with thick kitul jaggery syrup, coconut cream, eggs, nutmeg, cardamom, and roasted cashew nuts. Regular portion.",
      price: 4.99,
      originalPrice: 4.99,
      isOffer: false,
      ingredients: ["Kitul Jaggery", "Coconut Cream", "Eggs", "Nutmeg", "Cardamom", "Cashews"],
      allergens: ["Eggs", "Nuts"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_86",
      name: "Payasam",
      slug: "payasam",
      categoryId: { _id: "cat_11", name: "Desserts", slug: "desserts" },
      shortDescription: "Sweet milk pudding made with vermicelli, sago, cardamom, and raisins.",
      description: "South Indian sweet pudding made by boiling milk, sugar, vermicelli or sago, flavored with cardamoms, saffron, raisins, and roasted cashew nuts.",
      price: 4.99,
      originalPrice: 4.99,
      isOffer: false,
      ingredients: ["Milk", "Sugar", "Vermicelli", "Sago", "Cardamom", "Cashews", "Raisins"],
      allergens: ["Milk", "Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_87",
      name: "Ice Cream",
      slug: "ice-cream",
      categoryId: { _id: "cat_11", name: "Desserts", slug: "desserts" },
      shortDescription: "Generous scoop of vanilla, mango, or chocolate premium ice cream.",
      description: "Creamy premium ice cream scoops served chilled with a drizzle of syrup. Ask server for available flavors.",
      price: 4.99,
      originalPrice: 4.99,
      isOffer: false,
      ingredients: ["Milk Cream", "Sugar", "Flavors"],
      allergens: ["Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_88",
      name: "Caramel Pudding",
      slug: "caramel-pudding",
      categoryId: { _id: "cat_11", name: "Desserts", slug: "desserts" },
      shortDescription: "Classic velvety steamed custard with a golden liquid caramel top.",
      description: "Delectable homemade vanilla custard pudding with a soft caramel layer on top. Melt-in-your-mouth texture.",
      price: 4.99,
      originalPrice: 4.99,
      isOffer: false,
      ingredients: ["Eggs", "Milk", "Sugar", "Vanilla Extract"],
      allergens: ["Eggs", "Milk"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80" }],
    },

    // === CEYLON CURRY TREATS / SPECIAL MEALS ===
    {
      _id: "prod_89",
      name: "Rice and Mutton Curry with 2 Vegetable and Pappadam",
      slug: "rice-mutton-curry-combo",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Steamed rice with mutton curry, two seasonal vegetables, and crispy pappadam.",
      description: "A hearty daily lunch box featuring steamed white rice, authentic slow-cooked mutton curry, two seasonal Sri Lankan vegetable curries, and crispy pappadams.",
      price: 10.99,
      originalPrice: 10.99,
      isOffer: false,
      ingredients: ["Steamed White Rice", "Mutton Curry", "Seasonal Vegetables", "Pappadam"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_90",
      name: "Rice and Chicken Curry with 2 Vegetable and Pappadam",
      slug: "rice-chicken-curry-combo",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Steamed rice served with chicken curry, two vegetable curries, and pappadam.",
      description: "A balanced daily lunch box containing white rice, traditional Sri Lankan chicken curry, two seasonal vegetable curries, and crunchy pappadams.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Steamed White Rice", "Chicken Curry", "Seasonal Vegetables", "Pappadam"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_91",
      name: "Rice and Fish Curry with 2 Vegetable and Pappadam",
      slug: "rice-fish-curry-combo",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Steamed rice with tangy fish curry, two vegetable curries, and pappadam.",
      description: "Traditional coastal daily lunch box with steamed rice, spicy tangy fish curry cooked with tamarind, two vegetable curries, and pappadams.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: false,
      ingredients: ["Steamed White Rice", "Fish Curry", "Seasonal Vegetables", "Pappadam"],
      allergens: ["Fish"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_92",
      name: "Special Veg Thali – Friday",
      slug: "special-veg-thali-friday",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Friday Special: Elaborate vegetarian feast with white rice, 5 veg curries, rasam, and dessert.",
      description: "A grand Friday vegetarian thali. Steamed white rice served with five traditional vegetable curries, dal, rasam, pickle, pappadam, and a sweet payasam.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: true,
      offerPrice: 10.99,
      discountPercentage: 15,
      ingredients: ["Basmati Rice", "5 Veg Curries", "Dhal", "Rasam", "Pappadam", "Pickle", "Payasam"],
      allergens: ["Milk", "Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_93",
      name: "Ceylon Special Non Veg Thali – Friday",
      slug: "ceylon-special-non-veg-thali-friday",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Friday Special: Non-vegetarian thali featuring mutton curry, chicken curry, fish fry, and sides.",
      description: "Friday special platter with steamed rice, chicken curry, mutton curry, a piece of fried fish, vegetable curry, rasam, pappadam, and payasam.",
      price: 13.99,
      originalPrice: 13.99,
      isOffer: true,
      offerPrice: 11.99,
      discountPercentage: 14,
      ingredients: ["Basmati Rice", "Chicken Curry", "Mutton Curry", "Fried Fish Piece", "Rasam", "Pappadam", "Payasam"],
      allergens: ["Fish", "Milk", "Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_94",
      name: "Ceylon Special Lamp Rice Mutton – Saturday",
      slug: "ceylon-special-lamp-rice-mutton-saturday",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Saturday Special: Spiced rice and rich mutton curry baked in banana leaf (Lamprais).",
      description: "Dutch Burgher legacy dish. Aromatic ghee-rice, slow-cooked mutton curry, frikkadels (meatballs), seeni sambol, ash plantain, and boiled egg wrapped and baked in banana leaf. Available Saturdays only.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: false,
      ingredients: ["Ghee Rice", "Mutton Curry", "Frikkadels", "Seeni Sambol", "Ash Plantain", "Boiled Egg"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_95",
      name: "Ceylon Special Lamp Rice Chicken – Saturday",
      slug: "ceylon-special-lamp-rice-chicken-saturday",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Saturday Special: Fragrant rice and chicken curry baked in banana leaf (Lamprais).",
      description: "Aromatic ghee rice, savory chicken curry, frikkadel meatballs, seeni sambol, aubergine, and egg, wrapped inside banana leaf and baked. Saturdays only.",
      price: 12.99,
      originalPrice: 12.99,
      isOffer: false,
      ingredients: ["Ghee Rice", "Chicken Curry", "Frikkadels", "Seeni Sambol", "Aubergine", "Boiled Egg"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_96",
      name: "Unlimited Meal White Rice with Mutton/Chicken, 4 Veg Curries, Pappadam, Rasam",
      slug: "unlimited-meal-rice-curry",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "All-you-can-eat steamed rice served with chicken or mutton curry, 4 veg curries, rasam, and pappadam.",
      description: "Grand unlimited lunch meal! Steamed white rice with choice of mutton or chicken curry, four varieties of vegetarian curries, spiced rasam soup, and unlimited pappadams.",
      price: 14.99,
      originalPrice: 14.99,
      isOffer: false,
      ingredients: ["White Rice", "Chicken Curry", "Mutton Curry", "4 Veg Curries", "Rasam", "Pappadam"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_97",
      name: "Special Student Meal Rice with Chicken and Dhal/Leeks & Carrot Curry",
      slug: "special-student-meal",
      categoryId: { _id: "cat_12", name: "Ceylon Curry Treats / Special Meals", slug: "special-meals" },
      shortDescription: "Student Special: Rice served with chicken curry and choice of dhal or leeks & carrot curry.",
      description: "Budget-friendly student meal box. A generous portion of steamed white rice served with chicken curry and creamy dhal curry or sautéed leeks & carrot curry. (Student ID required).",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: true,
      offerPrice: 5.99,
      discountPercentage: 25,
      ingredients: ["White Rice", "Chicken Curry", "Dhal Curry", "Leeks & Carrot Curry"],
      allergens: [],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
  ],

  reservations: [] as any[],
  orders: [] as any[],
};
