// In-memory Store Fallback for Vercel production when MongoDB URI is not configured yet.

export const memoryStore = {
  settings: {
    _id: "default_settings_id",
    restaurantName: "Ceylon Curry",
    address: "44 Mayflower St, Plymouth PL1 1QX",
    mobileNumber: "01752 941504",
    whatsappNumber: "+441752941504",
    restaurantEmail: "info@ceyloncurry.co.uk",
    adminEmail: "admin@ceyloncurry.co.uk",
    openingHours: {
      monday: "12:00 PM - 10:00 PM",
      tuesday: "12:00 PM - 10:00 PM",
      wednesday: "12:00 PM - 10:00 PM",
      thursday: "12:00 PM - 10:00 PM",
      friday: "12:00 PM - 11:00 PM",
      saturday: "12:00 PM - 11:00 PM",
      sunday: "12:00 PM - 09:30 PM",
    },
    socialLinks: {
      facebook: "https://facebook.com/ceyloncurry",
      instagram: "https://instagram.com/ceyloncurry",
      tiktok: "https://tiktok.com/@ceyloncurry",
    },
    currency: "£",
    reservationSettings: {
      reservationDurationMinutes: 60,
      minNoticeHours: 1,
      maxAdvanceDays: 30,
    },
  },

  tables: [
    { _id: "tbl_1", tableNumber: 1, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_2", tableNumber: 2, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_3", tableNumber: 3, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_4", tableNumber: 4, capacity: 2, type: "Couple", status: "Available" },
    { _id: "tbl_5", tableNumber: 5, capacity: 4, type: "Family", status: "Available" },
    { _id: "tbl_6", tableNumber: 6, capacity: 4, type: "Family", status: "Available" },
    { _id: "tbl_7", tableNumber: 7, capacity: 4, type: "Family", status: "Available" },
  ],

  categories: [
    { _id: "cat_1", name: "Starters", slug: "starters", description: "Crispy rolls, cutlets and traditional Sri Lankan street bites", displayOrder: 1 },
    { _id: "cat_2", name: "Kottu", slug: "kottu", description: "Iconic Sri Lankan chopped flatbread tossed with vegetables, spices & curry", displayOrder: 2 },
    { _id: "cat_3", name: "Rice & Biryani", slug: "rice-biryani", description: "Aromatic basmati rice, lamprais & spiced biryani bowls", displayOrder: 3 },
    { _id: "cat_4", name: "Curries", slug: "curries", description: "Authentic roasted Ceylon spice curries cooked slowly with coconut milk", displayOrder: 4 },
    { _id: "cat_5", name: "Seafood", slug: "seafood", description: "Fresh Jaffna crab curry, devilled prawns and fried fish", displayOrder: 5 },
    { _id: "cat_6", name: "Vegetarian", slug: "vegetarian", description: "Plant-based curries, parathas, hoppers & dhal dishes", displayOrder: 6 },
    { _id: "cat_7", name: "Desserts", slug: "desserts", description: "Traditional Watalappan, coconut pudding and sweets", displayOrder: 7 },
    { _id: "cat_8", name: "Drinks", slug: "drinks", description: "Ceylon spiced tea, fresh mango lassi and refreshments", displayOrder: 8 },
  ],

  products: [
    {
      _id: "prod_1",
      name: "Chicken Kottu",
      slug: "chicken-kottu",
      categoryId: { _id: "cat_2", name: "Kottu", slug: "kottu" },
      shortDescription: "Chopped roti stir-fried with tender chicken, egg, fresh vegetables and aromatic Ceylon curry spices.",
      description: "Our signature dish! Fresh paratha roti shredded on a hot griddle and tossed with spiced chicken, farm eggs, leeks, onions, and curry sauce.",
      price: 12.00,
      originalPrice: 12.00,
      isOffer: false,
      ingredients: ["Chopped Roti", "Tender Chicken", "Eggs", "Onions", "Leeks", "Ceylon Spices"],
      allergens: ["Gluten", "Eggs"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "/images/chicken-kottu.jpg" }],
    },
    {
      _id: "prod_2",
      name: "Devilled Prawns",
      slug: "devilled-prawns",
      categoryId: { _id: "cat_5", name: "Seafood", slug: "seafood" },
      shortDescription: "Juicy king prawns sauteed with capsicum, tomatoes, and spicy sweet chili Ceylon sauce.",
      description: "Fresh tiger prawns fried and tossed in a fiery, sweet-and-sour Sri Lankan devilled glaze with crunchy peppers and onions.",
      price: 14.50,
      originalPrice: 14.50,
      isOffer: false,
      ingredients: ["King Prawns", "Bell Peppers", "Onions", "Chili Glaze", "Garlic", "Ginger"],
      allergens: ["Crustaceans", "Soy"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_3",
      name: "Jaffna Lamb Curry",
      slug: "jaffna-lamb-curry",
      categoryId: { _id: "cat_4", name: "Curries", slug: "curries" },
      shortDescription: "Slow-cooked boneless lamb infused with dark roasted Jaffna curry powder and coconut milk.",
      description: "Authentic Northern Sri Lankan style lamb curry simmered until melt-in-the-mouth tender with lemongrass, pandan leaves, and roasted spices.",
      price: 13.99,
      originalPrice: 13.99,
      isOffer: false,
      ingredients: ["Boneless Lamb", "Roasted Curry Powder", "Coconut Milk", "Lemongrass", "Pandan Leaf"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_4",
      name: "Ceylon Chicken Lamprais",
      slug: "ceylon-chicken-lamprais",
      categoryId: { _id: "cat_3", name: "Rice & Biryani", slug: "rice-biryani" },
      shortDescription: "Dutch Burgher delicacy: Ghee rice, spiced chicken curry, aubergine moju, and fried egg wrapped in banana leaf.",
      description: "Authentic Ceylon Lamprais baked inside a fragrant banana leaf parcel, sealing in rich aromas of ghee rice, frikkadels, chicken curry, and sweet aubergine.",
      price: 15.00,
      originalPrice: 15.00,
      isOffer: false,
      ingredients: ["Basmati Rice", "Chicken Curry", "Aubergine Moju", "Seeni Sambol", "Boiled Egg"],
      allergens: ["Eggs", "Mustard"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_5",
      name: "Mutton Rolls (3 Pcs)",
      slug: "mutton-rolls",
      categoryId: { _id: "cat_1", name: "Starters", slug: "starters" },
      shortDescription: "Crispy breaded short-crust rolls filled with spiced minced mutton and potato.",
      description: "Classic Sri Lankan street food starter. Crispy golden rolls stuffed with seasoned minced mutton, braised potatoes, and curry leaves.",
      price: 6.50,
      originalPrice: 6.50,
      isOffer: false,
      ingredients: ["Minced Mutton", "Potatoes", "Curry Leaves", "Breadcrumbs"],
      allergens: ["Gluten"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_6",
      name: "Sri Lankan Dhal Curry",
      slug: "sri-lankan-dhal-curry",
      categoryId: { _id: "cat_6", name: "Vegetarian", slug: "vegetarian" },
      shortDescription: "Creamy red lentils tempered with mustard seeds, curry leaves, garlic, and coconut milk.",
      description: "Essential Ceylon staple curry. Red split lentils cooked until smooth, tempered in coconut oil with fresh curry leaves, turmeric, and garlic.",
      price: 7.99,
      originalPrice: 7.99,
      isOffer: false,
      ingredients: ["Red Lentils", "Coconut Milk", "Mustard Seeds", "Turmeric", "Curry Leaves"],
      allergens: ["Mustard"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_7",
      name: "Watalappan",
      slug: "watalappan",
      categoryId: { _id: "cat_7", name: "Desserts", slug: "desserts" },
      shortDescription: "Traditional steamed coconut jaggery custard pudding spiced with cardamom and toasted cashews.",
      description: "Classic Sri Lankan royal dessert made with thick kitul jaggery syrup, coconut cream, eggs, nutmeg, cardamom, and roasted cashew nuts.",
      price: 5.50,
      originalPrice: 5.50,
      isOffer: false,
      ingredients: ["Kitul Jaggery", "Coconut Milk", "Eggs", "Cardamom", "Cashews"],
      allergens: ["Eggs", "Nuts"],
      isAvailable: true,
      isFeatured: false,
      images: [{ url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80" }],
    },
    {
      _id: "prod_8",
      name: "Veg Thali",
      slug: "veg-thali",
      categoryId: { _id: "cat_3", name: "Rice & Biryani", slug: "rice-biryani" },
      shortDescription: "A traditional Sri Lankan vegetarian platter with rice, papadum, dhal, and assorted vegetable curries.",
      description: "A complete Sri Lankan meal served on a platter. Includes steamed basmati rice, crispy papadum, creamy red lentil dhal, and three seasonal vegetable curries packed with authentic spices.",
      price: 9.99,
      originalPrice: 9.99,
      isOffer: true,
      offerPrice: 7.99,
      discountPercentage: 20,
      ingredients: ["Basmati Rice", "Red Lentil Dhal", "Seasonal Vegetables", "Papadum", "Spices"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "/images/veg-thali.jpg" }],
    },
    {
      _id: "prod_9",
      name: "Non Veg Thali",
      slug: "non-veg-thali",
      categoryId: { _id: "cat_3", name: "Rice & Biryani", slug: "rice-biryani" },
      shortDescription: "A traditional Sri Lankan non-vegetarian platter with rice, papadum, dhal, chicken curry, and mutton curry.",
      description: "A rich and complete Sri Lankan non-vegetarian platter. Includes steamed basmati rice, crispy papadum, creamy red lentil dhal, devilled vegetables, authentic chicken curry, and slow-cooked mutton curry.",
      price: 13.99,
      originalPrice: 13.99,
      isOffer: true,
      offerPrice: 10.99,
      discountPercentage: 21,
      ingredients: ["Basmati Rice", "Chicken Curry", "Mutton Curry", "Red Lentil Dhal", "Papadum", "Spices"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "/images/non-veg-thali.jpg" }],
    },
    {
      _id: "prod_10",
      name: "Rice & 4 Veg Curry",
      slug: "rice-4-veg-curry",
      categoryId: { _id: "cat_6", name: "Vegetarian", slug: "vegetarian" },
      shortDescription: "Steamed basmati rice served with four varieties of traditional Sri Lankan vegetable curries.",
      description: "A wholesome and healthy plate of steamed basmati rice accompanied by four different authentic Sri Lankan vegetable curries, tempered red lentils, seeni sambol, and papadum.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: true,
      offerPrice: 4.99,
      discountPercentage: 28,
      ingredients: ["Basmati Rice", "Dhal Curry", "Aubergine Moju", "Pol Sambol", "Potato Curry", "Papadum"],
      allergens: [],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "/images/rice-4-veg-curry.jpg" }],
    },
    {
      _id: "prod_11",
      name: "Rice & Fish Curry",
      slug: "rice-fish-curry",
      categoryId: { _id: "cat_5", name: "Seafood", slug: "seafood" },
      shortDescription: "Steamed basmati rice served with authentic Sri Lankan fish curry and side curries.",
      description: "Fragrant steamed basmati rice served with a rich, tangy, and spicy traditional Sri Lankan fish curry cooked in coconut milk, paired with dhal curry, seeni sambol, and papadum.",
      price: 6.99,
      originalPrice: 6.99,
      isOffer: true,
      offerPrice: 4.99,
      discountPercentage: 28,
      ingredients: ["Basmati Rice", "Ceylon Fish Curry", "Red Lentil Dhal", "Seeni Sambol", "Papadum"],
      allergens: ["Fish"],
      isAvailable: true,
      isFeatured: true,
      images: [{ url: "/images/rice-fish-curry.jpg" }],
    },
  ],

  reservations: [] as any[],
  orders: [] as any[],
};
