"use client";

import React, { useEffect, useState } from "react";
import { ShoppingBag, MessageCircle, Clock } from "lucide-react";

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchOrders();
  }, []);

  const fetchOrders = async () => {
    try {
      const res = await fetch("/api/orders");
      const data = await res.json();
      if (data.success) setOrders(data.orders);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center pb-4 border-b border-gray-200">
        <div>
          <h1 className="font-display text-3xl font-extrabold text-ceylon-blue">
            WhatsApp Orders Log
          </h1>
          <p className="text-xs text-gray-500 mt-1">
            Operational record of orders generated by customers for WhatsApp checkout.
          </p>
        </div>
      </div>

      {loading ? (
        <div className="bg-white rounded-2xl p-12 text-center">
          <div className="animate-spin w-8 h-8 border-4 border-ceylon-blue border-t-ceylon-gold rounded-full mx-auto" />
        </div>
      ) : orders.length === 0 ? (
        <div className="bg-white rounded-2xl p-12 text-center max-w-md mx-auto space-y-2 border">
          <p className="font-bold text-gray-700">No Orders Logged</p>
          <p className="text-xs text-gray-500">Orders submitted via checkout will appear here.</p>
        </div>
      ) : (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-ceylon-cream text-ceylon-blue text-xs uppercase font-extrabold border-b border-gray-200">
                  <th className="p-4">Order Ref</th>
                  <th className="p-4">Customer</th>
                  <th className="p-4">Delivery Address</th>
                  <th className="p-4">Total</th>
                  <th className="p-4">Date</th>
                  <th className="p-4">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 text-sm">
                {orders.map((o) => (
                  <tr key={o._id} className="hover:bg-gray-50/50">
                    <td className="p-4 font-mono font-bold text-ceylon-blue text-xs">{o.orderNumber}</td>
                    <td className="p-4">
                      <span className="font-bold text-gray-900 block">{o.customerName}</span>
                      <span className="text-xs text-gray-500 block">{o.mobile}</span>
                    </td>
                    <td className="p-4 text-xs text-gray-700 max-w-xs truncate">{o.address}</td>
                    <td className="p-4 font-bold text-ceylon-blue">£{o.total.toFixed(2)}</td>
                    <td className="p-4 text-xs text-gray-500">
                      {new Date(o.createdAt).toLocaleDateString()}
                    </td>
                    <td className="p-4">
                      <span className="px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold inline-flex items-center gap-1">
                        <MessageCircle className="w-3 h-3" /> WhatsApp Prepared
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
